### ISSUE TITLE
Check for Illegal character in path

### ISSUE THREAD

**Issue by Orski174** [maforget/Folder-Icon-Creator#1]
So as stated in the title, it works for movies and shows but when it comes to anime it returns this:

Processing File : O:\!Hard links!\Anime Main\Rurouni Kenshin: Meiji Kenkaku Romantan - Seisou Hen\folder.jpg
Creating Icon : O:\!Hard links!\Anime Main\Rurouni Kenshin: Meiji Kenkaku Romantan - Seisou Hen\folder.ico
Creating desktop.ini File
Setting desktop.ini Attributes
`
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'O:\!Hard links!\Anime Main\Rurouni Kenshin: Meiji Kenkaku Romantan - Seisou Hen\desktop.ini'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at Folder_Icon_Creator.Program.SetIniFileAttributes(String ini)
   at Folder_Icon_Creator.Program.ProcessFolderJPGs()
   at Folder_Icon_Creator.Program.CreateIconFromFolders(List1 folderList, Options options)
   at Folder_Icon_Creator.Program.DoCoreTask(Options options)
   at Folder_Icon_Creator.Program.Main(String[] args)
`

Though I should mention that sometimes it works, but just for a couple folders, I really have no idea why.

Working example :
`
Processing File : O:\!Hard links!\Anime Main\Seishun Buta Yarou wa Yumemiru Shoujo no Yume o Minai\folder.jpg
Creating Icon : O:\!Hard links!\Anime Main\Seishun Buta Yarou wa Yumemiru Shoujo no Yume o Minai\folder.ico
Creating desktop.ini File
Setting desktop.ini Attributes
Setting Folder Attributes
Setting Icon To Folder: O:\!Hard links!\Anime Main\Seishun Buta Yarou wa Yumemiru Shoujo no Yume o Minai
`

**Comment by maforget** [comment]
The `:` is an illegal character in windows. You shouldn't even be able to create a folder with that character in it. Also the program has little error checking and by the time it's trying to access the .ini file, it was never created in the first place.

Based on your log it should have created the folder.ico, but I am thinking it may not have done so either.

Some more error checking should be in order.

**Comment by Orski174** [comment]
You're right, it only happens for folders with `:` in them.
These folders are automatically created by another service so maybe they have a workaround to write them.
Thank you for your help, do you think it's possible to make something to read it anyways?

**Comment by maforget** [comment]
I would simply rename them, nothing will work with this. I don't even know if Linux supports these. It isn't really worth the hassle.

**Comment by Orski174** [comment]
Thank you, that's what I did.
